# Generated by Django 5.0.1 on 2024-02-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetly_text_rephrase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
