# Generated by Django 5.0.1 on 2024-02-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetly_text_rephrase', '0002_text_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='original_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
