# Generated by Django 5.0.1 on 2024-02-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacetly_text_rephrase', '0004_remove_textrepharseimage_is_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='font_color',
        ),
        migrations.RemoveField(
            model_name='text',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='text',
            name='text_alignment',
        ),
    ]
