# Generated by Django 5.0.1 on 2024-03-12 01:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this article, generated automatically.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time when this article was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this article was last updated.')),
                ('step0', models.JSONField(default=dict, help_text='Step 0 content')),
                ('step1', models.JSONField(default=dict, help_text='Step 1 content')),
                ('step2', models.JSONField(default=dict, help_text='Step 2 content')),
                ('step3', models.JSONField(default=dict, help_text='Step 3 content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
