# Generated by Django 5.0.1 on 2024-03-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetly_articleGenerator', '0002_alter_articles_options_articles_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='step0',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='step1',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='step2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='step3',
        ),
        migrations.AddField(
            model_name='articles',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='selected_subtitles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, help_text='Article title', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='tone_of_voice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
