# Generated by Django 5.0.1 on 2024-03-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacetly_articleGenerator', '0003_remove_articles_step0_remove_articles_step1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='selected_subtitles',
            new_name='subtitles',
        ),
    ]
