# Generated by Django 5.0.1 on 2024-03-12 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_document_editor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MutqinAssistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template', models.CharField(choices=[('productAds_prompt', 'productAds_prompt'), ('writeEmail_prompt', 'writeEmail_prompt'), ('customerServiceQA_prompt', 'customerServiceQA_prompt'), ('companyMissionDetails_prompt', 'companyMissionDetails_prompt'), ('BlogThoughts_prompt', 'BlogThoughts_prompt'), ('newsReleaseDetails_prompt', 'newsReleaseDetails_prompt'), ('searchKeywords_prompt', 'searchKeywords_prompt'), ('videoIllustrationScript_prompt', 'videoIllustrationScript_prompt'), ('podcastScript_prompt', 'podcastScript_prompt'), ('webinarScript_prompt', 'webinarScript_prompt'), ('caseStudiesScript_prompt', 'caseStudiesScript_prompt'), ('historyVideoScript_prompt', 'historyVideoScript_prompt'), ('virtualEventScript_prompt', 'virtualEventScript_prompt'), ('newsletterScript_prompt', 'newsletterScript_prompt'), ('tvAdsScript_prompt', 'tvAdsScript_prompt'), ('businessIdeasScript_prompt', 'businessIdeasScript_prompt'), ('souqSuggestionScript_prompt', 'souqSuggestionScript_prompt'), ('currentTrends_prompt', 'currentTrends_prompt'), ('lowCostBusinessIdeas_prompt', 'lowCostBusinessIdeas_prompt'), ('telecommutingBusinessIdeas_prompt', 'telecommutingBusinessIdeas_prompt')], max_length=100)),
                ('qeuestion', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_document_editor.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutqin_assistant_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
