# Generated by Django 5.0.1 on 2024-03-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutqin_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutqinassistant',
            name='template',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
