# Generated by Django 5.0.1 on 2024-03-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutqin_assistant', '0003_mutqinassistant_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutqinassistant',
            old_name='qeuestion',
            new_name='question',
        ),
    ]
