# Generated by Django 5.0.1 on 2024-03-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetly_templates', '0008_usertemplate_favorite_delete_favoritetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertemplate',
            name='favorite',
        ),
        migrations.AddField(
            model_name='template',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
