# Generated by Django 5.0.1 on 2024-03-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetly_templates', '0009_remove_usertemplate_favorite_template_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatespecificationfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('textarea', 'Textarea')], default='text', max_length=20),
        ),
    ]
