# Generated by Django 5.0.1 on 2024-03-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetly_templates', '0011_favoritetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemplate',
            name='language',
            field=models.CharField(default='en', max_length=100),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='target_audience',
            field=models.CharField(default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='tone_of_voice',
            field=models.CharField(default='neutral', max_length=100),
        ),
    ]
