# Generated by Django 5.0.1 on 2024-03-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacetly_templates', '0012_alter_usertemplate_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertemplate',
            options={'ordering': ['-created_at']},
        ),
    ]
