# Generated by Django 5.0.1 on 2024-03-18 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_document_editor', '0001_initial'),
        ('spacetly_templates', '0013_alter_usertemplate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemplate',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_document_editor.document'),
        ),
    ]
