# Generated by Django 5.0.1 on 2024-03-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacetly_templates', '0014_usertemplate_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertemplate',
            old_name='output_data',
            new_name='content',
        ),
    ]
