# Generated by Django 5.0.1 on 2024-02-04 08:46

import apps.spacetly_chatbot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigIntegerField(default=apps.spacetly_chatbot.models.generate_secure_random_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Empty', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favourite', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('ended', 'Ended')], default='active', max_length=10)),
                ('ai_model', models.CharField(choices=[('ChatGPT', 'ChatGPT (Free)'), ('GPT4', 'GPT4 (Paid)'), ('Google PalM 2', 'Google PalM 2 (Paid)')], default='ChatGPT', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_from_user', models.BooleanField(default=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacetly_chatbot.conversation')),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='spacetly_chatbot.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
