# Generated by Django 5.0.1 on 2024-02-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetly_chatbot', '0002_message_file_message_image_message_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='ai_model',
            field=models.CharField(choices=[('ChatGPT', 'ChatGPT (Free)'), ('GPT4', 'GPT4 (Paid)'), ('Google PalM 2', 'Google PalM 2 (Paid)')], default='Google PalM 2', max_length=50),
        ),
    ]
