# Generated by Django 5.0.1 on 2024-02-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetly_grammmer_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='New Document', max_length=100),
        ),
    ]
