# Generated by Django 5.0.1 on 2024-02-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_gene',
            name='image_paths',
            field=models.JSONField(default=dict),
        ),
    ]
