# Generated by Django 5.0.1 on 2024-03-05 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0002_alter_image_gene_image_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_gene',
            name='num_of_image',
        ),
        migrations.RemoveField(
            model_name='image_gene',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='image_gene',
            name='style',
        ),
    ]
